/*
 * Cronz - https://lib.cronz.dev
 *
 * Copyright (c) 2024 - present. All rights reserved.
 * Tuğrul Güngör - https://tugrulgungor.me
 *
 * Distributed under the MIT License.
 * https://opensource.org/license/mit/
 */

#include <cronz/crypto/hex.hpp>

#include <gtest/gtest.h>

TEST(URL, Hex) {
    constexpr std::array<std::tuple<std::uint8_t, char, char>, static_cast<std::size_t>(256)> bnn = {
            std::make_tuple(static_cast<std::uint8_t>(0), '0', '0'),
            std::make_tuple(static_cast<std::uint8_t>(1), '0', '1'),
            std::make_tuple(static_cast<std::uint8_t>(2), '0', '2'),
            std::make_tuple(static_cast<std::uint8_t>(3), '0', '3'),
            std::make_tuple(static_cast<std::uint8_t>(4), '0', '4'),
            std::make_tuple(static_cast<std::uint8_t>(5), '0', '5'),
            std::make_tuple(static_cast<std::uint8_t>(6), '0', '6'),
            std::make_tuple(static_cast<std::uint8_t>(7), '0', '7'),
            std::make_tuple(static_cast<std::uint8_t>(8), '0', '8'),
            std::make_tuple(static_cast<std::uint8_t>(9), '0', '9'),
            std::make_tuple(static_cast<std::uint8_t>(10), '0', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(11), '0', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(12), '0', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(13), '0', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(14), '0', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(15), '0', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(16), '1', '0'),
            std::make_tuple(static_cast<std::uint8_t>(17), '1', '1'),
            std::make_tuple(static_cast<std::uint8_t>(18), '1', '2'),
            std::make_tuple(static_cast<std::uint8_t>(19), '1', '3'),
            std::make_tuple(static_cast<std::uint8_t>(20), '1', '4'),
            std::make_tuple(static_cast<std::uint8_t>(21), '1', '5'),
            std::make_tuple(static_cast<std::uint8_t>(22), '1', '6'),
            std::make_tuple(static_cast<std::uint8_t>(23), '1', '7'),
            std::make_tuple(static_cast<std::uint8_t>(24), '1', '8'),
            std::make_tuple(static_cast<std::uint8_t>(25), '1', '9'),
            std::make_tuple(static_cast<std::uint8_t>(26), '1', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(27), '1', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(28), '1', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(29), '1', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(30), '1', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(31), '1', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(32), '2', '0'),
            std::make_tuple(static_cast<std::uint8_t>(33), '2', '1'),
            std::make_tuple(static_cast<std::uint8_t>(34), '2', '2'),
            std::make_tuple(static_cast<std::uint8_t>(35), '2', '3'),
            std::make_tuple(static_cast<std::uint8_t>(36), '2', '4'),
            std::make_tuple(static_cast<std::uint8_t>(37), '2', '5'),
            std::make_tuple(static_cast<std::uint8_t>(38), '2', '6'),
            std::make_tuple(static_cast<std::uint8_t>(39), '2', '7'),
            std::make_tuple(static_cast<std::uint8_t>(40), '2', '8'),
            std::make_tuple(static_cast<std::uint8_t>(41), '2', '9'),
            std::make_tuple(static_cast<std::uint8_t>(42), '2', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(43), '2', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(44), '2', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(45), '2', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(46), '2', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(47), '2', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(48), '3', '0'),
            std::make_tuple(static_cast<std::uint8_t>(49), '3', '1'),
            std::make_tuple(static_cast<std::uint8_t>(50), '3', '2'),
            std::make_tuple(static_cast<std::uint8_t>(51), '3', '3'),
            std::make_tuple(static_cast<std::uint8_t>(52), '3', '4'),
            std::make_tuple(static_cast<std::uint8_t>(53), '3', '5'),
            std::make_tuple(static_cast<std::uint8_t>(54), '3', '6'),
            std::make_tuple(static_cast<std::uint8_t>(55), '3', '7'),
            std::make_tuple(static_cast<std::uint8_t>(56), '3', '8'),
            std::make_tuple(static_cast<std::uint8_t>(57), '3', '9'),
            std::make_tuple(static_cast<std::uint8_t>(58), '3', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(59), '3', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(60), '3', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(61), '3', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(62), '3', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(63), '3', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(64), '4', '0'),
            std::make_tuple(static_cast<std::uint8_t>(65), '4', '1'),
            std::make_tuple(static_cast<std::uint8_t>(66), '4', '2'),
            std::make_tuple(static_cast<std::uint8_t>(67), '4', '3'),
            std::make_tuple(static_cast<std::uint8_t>(68), '4', '4'),
            std::make_tuple(static_cast<std::uint8_t>(69), '4', '5'),
            std::make_tuple(static_cast<std::uint8_t>(70), '4', '6'),
            std::make_tuple(static_cast<std::uint8_t>(71), '4', '7'),
            std::make_tuple(static_cast<std::uint8_t>(72), '4', '8'),
            std::make_tuple(static_cast<std::uint8_t>(73), '4', '9'),
            std::make_tuple(static_cast<std::uint8_t>(74), '4', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(75), '4', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(76), '4', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(77), '4', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(78), '4', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(79), '4', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(80), '5', '0'),
            std::make_tuple(static_cast<std::uint8_t>(81), '5', '1'),
            std::make_tuple(static_cast<std::uint8_t>(82), '5', '2'),
            std::make_tuple(static_cast<std::uint8_t>(83), '5', '3'),
            std::make_tuple(static_cast<std::uint8_t>(84), '5', '4'),
            std::make_tuple(static_cast<std::uint8_t>(85), '5', '5'),
            std::make_tuple(static_cast<std::uint8_t>(86), '5', '6'),
            std::make_tuple(static_cast<std::uint8_t>(87), '5', '7'),
            std::make_tuple(static_cast<std::uint8_t>(88), '5', '8'),
            std::make_tuple(static_cast<std::uint8_t>(89), '5', '9'),
            std::make_tuple(static_cast<std::uint8_t>(90), '5', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(91), '5', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(92), '5', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(93), '5', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(94), '5', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(95), '5', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(96), '6', '0'),
            std::make_tuple(static_cast<std::uint8_t>(97), '6', '1'),
            std::make_tuple(static_cast<std::uint8_t>(98), '6', '2'),
            std::make_tuple(static_cast<std::uint8_t>(99), '6', '3'),
            std::make_tuple(static_cast<std::uint8_t>(100), '6', '4'),
            std::make_tuple(static_cast<std::uint8_t>(101), '6', '5'),
            std::make_tuple(static_cast<std::uint8_t>(102), '6', '6'),
            std::make_tuple(static_cast<std::uint8_t>(103), '6', '7'),
            std::make_tuple(static_cast<std::uint8_t>(104), '6', '8'),
            std::make_tuple(static_cast<std::uint8_t>(105), '6', '9'),
            std::make_tuple(static_cast<std::uint8_t>(106), '6', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(107), '6', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(108), '6', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(109), '6', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(110), '6', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(111), '6', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(112), '7', '0'),
            std::make_tuple(static_cast<std::uint8_t>(113), '7', '1'),
            std::make_tuple(static_cast<std::uint8_t>(114), '7', '2'),
            std::make_tuple(static_cast<std::uint8_t>(115), '7', '3'),
            std::make_tuple(static_cast<std::uint8_t>(116), '7', '4'),
            std::make_tuple(static_cast<std::uint8_t>(117), '7', '5'),
            std::make_tuple(static_cast<std::uint8_t>(118), '7', '6'),
            std::make_tuple(static_cast<std::uint8_t>(119), '7', '7'),
            std::make_tuple(static_cast<std::uint8_t>(120), '7', '8'),
            std::make_tuple(static_cast<std::uint8_t>(121), '7', '9'),
            std::make_tuple(static_cast<std::uint8_t>(122), '7', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(123), '7', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(124), '7', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(125), '7', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(126), '7', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(127), '7', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(128), '8', '0'),
            std::make_tuple(static_cast<std::uint8_t>(129), '8', '1'),
            std::make_tuple(static_cast<std::uint8_t>(130), '8', '2'),
            std::make_tuple(static_cast<std::uint8_t>(131), '8', '3'),
            std::make_tuple(static_cast<std::uint8_t>(132), '8', '4'),
            std::make_tuple(static_cast<std::uint8_t>(133), '8', '5'),
            std::make_tuple(static_cast<std::uint8_t>(134), '8', '6'),
            std::make_tuple(static_cast<std::uint8_t>(135), '8', '7'),
            std::make_tuple(static_cast<std::uint8_t>(136), '8', '8'),
            std::make_tuple(static_cast<std::uint8_t>(137), '8', '9'),
            std::make_tuple(static_cast<std::uint8_t>(138), '8', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(139), '8', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(140), '8', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(141), '8', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(142), '8', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(143), '8', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(144), '9', '0'),
            std::make_tuple(static_cast<std::uint8_t>(145), '9', '1'),
            std::make_tuple(static_cast<std::uint8_t>(146), '9', '2'),
            std::make_tuple(static_cast<std::uint8_t>(147), '9', '3'),
            std::make_tuple(static_cast<std::uint8_t>(148), '9', '4'),
            std::make_tuple(static_cast<std::uint8_t>(149), '9', '5'),
            std::make_tuple(static_cast<std::uint8_t>(150), '9', '6'),
            std::make_tuple(static_cast<std::uint8_t>(151), '9', '7'),
            std::make_tuple(static_cast<std::uint8_t>(152), '9', '8'),
            std::make_tuple(static_cast<std::uint8_t>(153), '9', '9'),
            std::make_tuple(static_cast<std::uint8_t>(154), '9', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(155), '9', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(156), '9', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(157), '9', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(158), '9', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(159), '9', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(160), 'A', '0'),
            std::make_tuple(static_cast<std::uint8_t>(161), 'A', '1'),
            std::make_tuple(static_cast<std::uint8_t>(162), 'A', '2'),
            std::make_tuple(static_cast<std::uint8_t>(163), 'A', '3'),
            std::make_tuple(static_cast<std::uint8_t>(164), 'A', '4'),
            std::make_tuple(static_cast<std::uint8_t>(165), 'A', '5'),
            std::make_tuple(static_cast<std::uint8_t>(166), 'A', '6'),
            std::make_tuple(static_cast<std::uint8_t>(167), 'A', '7'),
            std::make_tuple(static_cast<std::uint8_t>(168), 'A', '8'),
            std::make_tuple(static_cast<std::uint8_t>(169), 'A', '9'),
            std::make_tuple(static_cast<std::uint8_t>(170), 'A', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(171), 'A', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(172), 'A', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(173), 'A', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(174), 'A', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(175), 'A', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(176), 'B', '0'),
            std::make_tuple(static_cast<std::uint8_t>(177), 'B', '1'),
            std::make_tuple(static_cast<std::uint8_t>(178), 'B', '2'),
            std::make_tuple(static_cast<std::uint8_t>(179), 'B', '3'),
            std::make_tuple(static_cast<std::uint8_t>(180), 'B', '4'),
            std::make_tuple(static_cast<std::uint8_t>(181), 'B', '5'),
            std::make_tuple(static_cast<std::uint8_t>(182), 'B', '6'),
            std::make_tuple(static_cast<std::uint8_t>(183), 'B', '7'),
            std::make_tuple(static_cast<std::uint8_t>(184), 'B', '8'),
            std::make_tuple(static_cast<std::uint8_t>(185), 'B', '9'),
            std::make_tuple(static_cast<std::uint8_t>(186), 'B', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(187), 'B', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(188), 'B', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(189), 'B', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(190), 'B', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(191), 'B', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(192), 'C', '0'),
            std::make_tuple(static_cast<std::uint8_t>(193), 'C', '1'),
            std::make_tuple(static_cast<std::uint8_t>(194), 'C', '2'),
            std::make_tuple(static_cast<std::uint8_t>(195), 'C', '3'),
            std::make_tuple(static_cast<std::uint8_t>(196), 'C', '4'),
            std::make_tuple(static_cast<std::uint8_t>(197), 'C', '5'),
            std::make_tuple(static_cast<std::uint8_t>(198), 'C', '6'),
            std::make_tuple(static_cast<std::uint8_t>(199), 'C', '7'),
            std::make_tuple(static_cast<std::uint8_t>(200), 'C', '8'),
            std::make_tuple(static_cast<std::uint8_t>(201), 'C', '9'),
            std::make_tuple(static_cast<std::uint8_t>(202), 'C', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(203), 'C', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(204), 'C', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(205), 'C', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(206), 'C', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(207), 'C', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(208), 'D', '0'),
            std::make_tuple(static_cast<std::uint8_t>(209), 'D', '1'),
            std::make_tuple(static_cast<std::uint8_t>(210), 'D', '2'),
            std::make_tuple(static_cast<std::uint8_t>(211), 'D', '3'),
            std::make_tuple(static_cast<std::uint8_t>(212), 'D', '4'),
            std::make_tuple(static_cast<std::uint8_t>(213), 'D', '5'),
            std::make_tuple(static_cast<std::uint8_t>(214), 'D', '6'),
            std::make_tuple(static_cast<std::uint8_t>(215), 'D', '7'),
            std::make_tuple(static_cast<std::uint8_t>(216), 'D', '8'),
            std::make_tuple(static_cast<std::uint8_t>(217), 'D', '9'),
            std::make_tuple(static_cast<std::uint8_t>(218), 'D', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(219), 'D', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(220), 'D', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(221), 'D', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(222), 'D', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(223), 'D', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(224), 'E', '0'),
            std::make_tuple(static_cast<std::uint8_t>(225), 'E', '1'),
            std::make_tuple(static_cast<std::uint8_t>(226), 'E', '2'),
            std::make_tuple(static_cast<std::uint8_t>(227), 'E', '3'),
            std::make_tuple(static_cast<std::uint8_t>(228), 'E', '4'),
            std::make_tuple(static_cast<std::uint8_t>(229), 'E', '5'),
            std::make_tuple(static_cast<std::uint8_t>(230), 'E', '6'),
            std::make_tuple(static_cast<std::uint8_t>(231), 'E', '7'),
            std::make_tuple(static_cast<std::uint8_t>(232), 'E', '8'),
            std::make_tuple(static_cast<std::uint8_t>(233), 'E', '9'),
            std::make_tuple(static_cast<std::uint8_t>(234), 'E', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(235), 'E', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(236), 'E', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(237), 'E', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(238), 'E', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(239), 'E', 'F'),
            std::make_tuple(static_cast<std::uint8_t>(240), 'F', '0'),
            std::make_tuple(static_cast<std::uint8_t>(241), 'F', '1'),
            std::make_tuple(static_cast<std::uint8_t>(242), 'F', '2'),
            std::make_tuple(static_cast<std::uint8_t>(243), 'F', '3'),
            std::make_tuple(static_cast<std::uint8_t>(244), 'F', '4'),
            std::make_tuple(static_cast<std::uint8_t>(245), 'F', '5'),
            std::make_tuple(static_cast<std::uint8_t>(246), 'F', '6'),
            std::make_tuple(static_cast<std::uint8_t>(247), 'F', '7'),
            std::make_tuple(static_cast<std::uint8_t>(248), 'F', '8'),
            std::make_tuple(static_cast<std::uint8_t>(249), 'F', '9'),
            std::make_tuple(static_cast<std::uint8_t>(250), 'F', 'A'),
            std::make_tuple(static_cast<std::uint8_t>(251), 'F', 'B'),
            std::make_tuple(static_cast<std::uint8_t>(252), 'F', 'C'),
            std::make_tuple(static_cast<std::uint8_t>(253), 'F', 'D'),
            std::make_tuple(static_cast<std::uint8_t>(254), 'F', 'E'),
            std::make_tuple(static_cast<std::uint8_t>(255), 'F', 'F'),
    };

    // Test conversions
    for (const auto &[byte, n1, n2] : bnn) {
        auto byte_ = static_cast<std::uint8_t>(0);
        char n1_ = '\0';
        char n2_ = '\0';

        EXPECT_TRUE(Cronz::Crypto::HexToByte(n1, n2, byte_));
        EXPECT_EQ(byte, byte_);

        Cronz::Crypto::ByteToHex(byte, n1_, n2_);
        EXPECT_EQ(n1, n1_);
        EXPECT_EQ(n2, n2_);
    }

    // Test hex digits
    for (int value = static_cast<int>(CHAR_MIN); value <= static_cast<int>(CHAR_MAX); ++value) {
        const char character = static_cast<char>(value);
        const bool expectation = ('0' <= character && character <= '9') || ('a' <= character && character <= 'f') || (
            'A' <= character && character <= 'F');

        EXPECT_EQ(expectation, Cronz::Crypto::IsHexDigit(character));
    }
}

int main() {
    testing::InitGoogleTest();
    return RUN_ALL_TESTS();
}
